### ISSUE TITLE
Does not work for me...

### ISSUE THREAD

**Issue by crouti** [thewebsitedev/twd-mce-button#1]
Your code works until the ajax request, but then nothing is retrieved (although the list of post is correctly created) in the response.
Is it linked to the fact that you return something here:
`$posts = $this->posts( 'book' );
			return $posts;`

although nothing is returned by `posts` function ?
No problem for you in WP 4.7.3 ?
Thanks

**Comment by crouti** [comment]
I think the problem comes from the fact that the affectation of post list is made AFTER the tinymce add button script is made, so no value is set to listbox.
Can you confirm please ?

**Comment by thewebsitedev** [comment]
Hi there,

You need to change "book" to "post" on line 136 in twd-mce-button.php to get list of posts.

**Comment by crouti** [comment]
Yes this was done of course, but does not change the problem

**Comment by crouti** [comment]
Can you simply install you plugin on the latest WP version, and tell me if this works for you ? Not for me

**Comment by thewebsitedev** [comment]
Yes, I did try on the latest WP before replying.

**Comment by crouti** [comment]
Ok thanks, so it would be a conflict with another plugin or js library maybe...

**Comment by thewebsitedev** [comment]
quite possible.

**Comment by thewebsitedev** [comment]
The code has been updated. It might solve your issue.
