### ISSUE TITLE
Loads blank list

### ISSUE THREAD

**Issue by whatsnewsisyphus** [thewebsitedev/twd-mce-button#2]
Hello, I'm not sure if something got chucked in wordpress revisions since, but it's loading an empty list for me. I thought it was my modifications to the plugin but then I ran it as-is to query post type = post, alas, it was an empty dropdown. Nothing on the console or the debugger, network requests appear normal, though devoid of content (89 byte ajax requests to admin-ajax.php)

I don't think the document ready function is getting appended anyhwere as I tried manually populating the list with static content to be returned via ajax to no avail.

**Comment by thewebsitedev** [comment]
Hey, thanks! I will check and update soon.

**Comment by thewebsitedev** [comment]
Sorry, got too late. It seems to work fine in visual view but it doesn't work if you move from text view to visual view in the post editor.

**Comment by thewebsitedev** [comment]
Fixed! https://github.com/thewebsitedev/twd-mce-button/commit/540265e69f22aba9d403088dfb5df3f69dad794d
