### ISSUE TITLE
mce.js file error?

### ISSUE THREAD

**Issue by BobH42** [thewebsitedev/twd-mce-button#3]
I'm very new to this level of Wordpress coding but I was trying to use your wonderful code as a starting point and it wasn't working. I kept hacking at it and discovered that if I changed the 'values' line to 'values': tinyMCE.DOM.cptPostsList instead of the existing 'values': editor.settings.cptPostsList that the code worked perfectly. Did I miss something or was there a mistake here?

**Comment by thewebsitedev** [comment]
Yeah, good catch. 👍
